version: "3.7"

services:
  docker-compose-env:
    # build: .
    image: actorforth/docker-compose-env:v0.0.1
    environment:
      - HOST_SRC_PATH=${HOST_SRC_PATH}
    volumes:
      - ./components:/var/tmp/
      - ${HOST_SRC_PATH}/data/:/var/tmp/data
      - /var/run/docker.sock:/var/run/docker.sock
